object Versions {
    const val postgresql          = "42.2.23"
    const val flyway              = "7.11.2"
    const val spring              = "5.3.9"
    const val gradle              = "7.2"
    const val java                = "11"
    const val kotlin              = "1.5.30"
    const val assertJCore         = "3.17.2"
    const val junitJupiter        = "5.7.2"
    const val mapstruct           = "1.4.2.Final"
    const val mockitoCore         = "3.8.0"
    const val testcontainers      = "1.15.3"
    const val flywayGradlePlugin  = "7.0.0"
    const val kotlinLogging       = "2.0.11"
    const val jackson             = "2.12.4"
    const val springBoot          = "2.5.4"
    const val springDepManagement = "1.0.11.RELEASE"
    const val findbugsJsr305      = "3.0.2"
}
