object Versions {
    const val servlet             = "3.1.0"
    const val postgresql          = "42.2.23"
    const val flyway              = "7.11.2"
    const val hikariCP            = "5.0.0"
    const val spring              = "5.3.8"
    const val gradle              = "7.1.1"
    const val javaGlobal          = "11"
    const val kotlinLang          = "1.5.30"
    const val assertJCore         = "3.17.2"
    const val junitJupiter        = "5.7.2"
    const val mapstruct           = "1.4.2.Final"
    const val mockitoCore         = "3.8.0"
    const val testcontainers      = "1.15.3"
    const val flywayGradlePlugin  = "7.0.0"
    const val slf4j               = "1.7.30"
    const val logback             = "1.2.3"
    const val kotlinLogging       = "2.0.6"
    const val jackson             = "2.12.4"
    const val nodeJS              = "14.17.4"
    const val nodeJSGradlePlugin  = "3.0.1"
}
